service: map
image: blemli/map
volumes:
  - /opt/winterthur-data:/data
servers:
  web:
    hosts:
      - 185.66.109.77
proxy:
  ssl: true
  host: map.problem.li
  app_port: 5000
registry:
  username: blemli
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - WEBHOST_IP
  clear:
    NOMINATIM_URL: http://map-nominatim:8080
    OSRM_URL: http://map-osrm:5001

builder:
  arch:
    - amd64
ssh:
  config: true
  port: 2022
  user: deploy
aliases:
  apps: server exec docker exec kamal-proxy kamal-proxy list
  app_version: server exec "cd /opt/map && git tag --points-at HEAD"

accessories:
  winterthur-extractor:
    hosts:
      - 185.66.109.77
    image: blemli/winterthur-extractor
    volumes:
      - /opt/win$terthur-data:/data
  nominatim:
    service: nominatim   # Hostname = nominatim
    hosts:
      - 185.66.109.77
    image: mediagis/nominatim:4.3
    volumes:
      - /opt/winterthur-data:/nominatim/data
    env:
      clear:
        PBF_PATH: /nominatim/data/winterthur.osm.pbf
    port: "8080:8080"
  osrm:
    service: osrm
    hosts:
      - 185.66.109.77
    image: osrm/osrm-backend
    volumes:
      - /opt/winterthur-data:/data
    cmd: >
      sh -c "
      osrm-extract -p /opt/bicycle.lua /data/winterthur.osm.pbf &&
      osrm-partition /data/winterthur.osrm &&
      osrm-customize /data/winterthur.osrm &&
      osrm-routed --algorithm mld -p 5001 /data/winterthur.osrm
      "
    port: "5001:5001"
