service: map
image: blemli/map
volumes:
  - /opt/winterthur-data:/data
servers:
  web:
    hosts:
      - 185.66.109.77
proxy:
  ssl: true
  host: map.problem.li
  app_port: 5000
registry:
  username: blemli
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - WEBHOST_IP
    env:
  clear:
    NOMINATIM_URL: http://search:8080

builder:
  arch:
    - amd64
ssh:
  config: true
  port: 2022
  user: deploy
aliases:
  apps: server exec docker exec kamal-proxy kamal-proxy list
  app_version: server exec "cd /opt/map && git tag --points-at HEAD"
accessories:
  winterthur-extractor:
    hosts:
      - 185.66.109.77
    image: blemli/winterthur-extractor
    volumes:
      - /opt/winterthur-data:/data
    search:
      hosts:
        - 185.66.109.77
      image: mediagis/nominatim:4.3
      volumes:
        - /opt/winterthur-data:/nominatim/data
      env:
        - PBF_PATH=/nominatim/data/winterthur.osm.pbf
      port: "8080:8080"
